# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/main
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
          command: |
            R -e 'devtools:::install_deps(dependencies = TRUE)'
      - run:
          command: |
            R -e 'install.packages("testthat")'
      - run:
          command: |
            R -e 'devtools::install_github("jimhester/lintr")'
      - run:
          command: |
            R -e 'devtools::check()'
      - run:
          command: |
            R -e 'devtools::test()'
      - store_artifacts:
          path: man/
          destination: man
