# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/r-ver:4.2.1
    steps:
      - checkout
      - run: sudo yum install libxml2
      - run:
          command: |
            R -e 'install.packages(c("devtools","testthat","purrr","jsonlite","stringr","httr","urltools","tidyverse"))'
      - run:
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
          command: |
            R -e 'devtools::test()'
      - store_artifacts:
          path: man/
          destination: man
